spring:
  application:
    name: ms-gestion-hoja-de-vida

  config:
    import: optional:file:.env[.properties]

  profiles:
    default: dev

  jpa:
    open-in-view: false

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      max-file-size: ${HOJA_VIDA_RESOLUTION_MAX_SIZE:5MB}
      max-request-size: ${HOJA_VIDA_MAX_REQUEST_SIZE:6MB}

app:
  archivos:
    resolucion:
      tamano-maximo: ${HOJA_VIDA_RESOLUTION_MAX_SIZE:5MB}
